# Generated by Django 3.2.5 on 2021-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nutrifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(max_length=100)),
                ('Serving', models.CharField(max_length=100)),
                ('Calories', models.CharField(max_length=100)),
                ('Carbs', models.CharField(max_length=100)),
                ('Total_Fats', models.CharField(max_length=100)),
                ('Sat_fats', models.CharField(max_length=100)),
                ('Trans_Fat', models.CharField(max_length=100)),
                ('Chol', models.CharField(max_length=100)),
                ('Fiber', models.CharField(max_length=100)),
                ('Sugar', models.CharField(max_length=100)),
                ('Protien', models.CharField(max_length=100)),
                ('Calcium', models.CharField(max_length=100)),
                ('Iron', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='befit_users',
        ),
    ]
