# Generated by Django 3.2.5 on 2021-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befitapp', '0004_exercise_proexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('bline', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
    ]
