# Generated by Django 3.2.5 on 2021-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befitapp', '0006_profileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
            ],
        ),
    ]
