# Generated by Django 3.2.5 on 2021-07-24 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('befitapp', '0008_auto_20210723_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='plmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pemeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pdmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pbmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=100)),
                ('cal', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
